 # Using met.no forecasts with weather-tools



 This notebook-style script shows how to fetch met.no forecasts and combine them

 with SILO observations using the new `weather_tools` APIs. Open it directly in

 JupyterLab or VS Code with Jupytext to run the cells interactively.

 ## Prerequisites

 - Network access to `https://api.met.no` and a valid contact e-mail for the User-Agent header.

 - Set `SILO_API_KEY` (your registered SILO e-mail) or pass `api_key=` directly to `SiloAPI`.

 - Install `weather-tools` in your environment (either via `pip install weather-tools` or the local checkout).

 - Optional: enable logging (e.g. `logging.basicConfig(level=logging.INFO)`) to inspect requests.

In [1]:
import pandas as pd

from weather_tools.merge_weather_data import get_merge_summary, merge_historical_and_forecast
from weather_tools.metno_api import MetNoAPI
from weather_tools.metno_models import MetNoFormat, MetNoQuery
from weather_tools.silo_api import SiloAPI
from weather_tools.silo_models import AustralianCoordinates

In [2]:
# silo_api = SiloAPI(log_level="INFO")
# station_meta = silo_api.search_stations("Northam").iloc[0]

station_meta = {
    "station_code": 10111,
    "name": "NORTHAM",
    "latitude": -31.651,
    "longitude": 116.659,
    "state": "WA",
    "elevation": 170.0,
}

## 1. Configure the met.no API client

 met.no requires a descriptive User-Agent string that includes contact details.

 Replace the placeholder below with your own application name and e-mail.

In [3]:
api = MetNoAPI(
    # user_agent="weather-tools-example/0.1 (contact: you@example.com)",
    enable_cache=True,
    log_level="DEBUG",
)

## 2. Build a forecast query for your location

 The `AustralianCoordinates` model validates that the latitude and longitude sit

 within the range supported by SILO (GDA94 datum). Adjust the coordinates to

 target your site of interest.

In [4]:
coordinates = AustralianCoordinates(
    latitude=station_meta["latitude"], longitude=station_meta["longitude"]
)  # Northam, WA
query = MetNoQuery(coordinates=coordinates, format=MetNoFormat.COMPACT)

response = api.query_forecast(query)
metadata = response.get_meta()

metadata

[05/27/26 20:21:07] DEBUG    🌐 Constructed URL:
                             https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=-31.651&lon=116.659

                    DEBUG    📋 User-Agent: weather-tools/0.0.0 (Python 3.13)

                    DEBUG    Making request (attempt 1/3):
                             https://api.met.no/weatherapi/locationforecast/2.0/compact

[05/27/26 20:21:08] DEBUG    Cached response for: e9450af0091badb1a028399707618845

                    DEBUG    Request successful on attempt 1

{'updated_at': '2026-05-27T11:15:56Z',
 'units': {'air_pressure_at_sea_level': 'hPa',
  'air_temperature': 'celsius',
  'cloud_area_fraction': '%',
  'precipitation_amount': 'mm',
  'relative_humidity': '%',
  'wind_from_direction': 'degrees',
  'wind_speed': 'm/s'}}

 ## 3. Convert forecasts to daily and hourly tables

 `MetNoAPI.to_dataframe` can aggregate the hourly GeoJSON payload to daily summaries

 or return hourly data. Use the `frequency` parameter to control aggregation:

 - `frequency='daily'` (default) - Daily aggregates

 - `frequency='hourly'` - Raw hourly data

 - `frequency='weekly'` or `frequency='monthly'` - Other time periods

In [5]:
daily_forecasts = api.to_dataframe(response, daily=True)
hourly_forecasts = api.to_dataframe(response, daily=False)

daily_forecasts.head()

,date,daily_rain,max_temp,min_temp,mslp,relative_humidity,wind_speed,wind_speed_max,cloud_fraction,weather_symbol
0,2026-05-27,7.3,16.2,13.5,1013.358333,64.608333,4.316667,5.6,67.183333,heavyrainshowers_night
1,2026-05-28,0.3,20.1,9.2,1015.487500,80.341667,3.266667,6.1,25.883333,lightrainshowers_day
2,2026-05-29,0.1,18.8,9.4,1016.166667,77.612500,2.050000,3.9,58.820833,lightrainshowers_day
3,2026-05-30,8.0,19.5,10.5,1008.700000,77.375000,4.275000,6.6,42.575000,lightrainshowers_day
4,2026-05-31,8.8,14.8,10.5,1002.175000,82.250000,8.200000,9.1,56.225000,rainshowers_day

In [6]:
hourly_forecasts.head()

,time,air_pressure_at_sea_level,air_temperature,cloud_area_fraction,relative_humidity,wind_from_direction,wind_speed,precipitation_amount,symbol_code
0,2026-05-27 12:00:00,1015.2,15.7,23.4,42.6,320.8,2.7,0.0,fair_night
1,2026-05-27 13:00:00,1015.1,14.2,50.8,45.3,327.9,2.7,0.0,partlycloudy_night
2,2026-05-27 14:00:00,1014.9,14.0,100.0,44.9,327.6,3.1,0.0,cloudy
3,2026-05-27 15:00:00,1014.4,16.0,93.0,38.7,319.0,5.3,0.0,cloudy
4,2026-05-27 16:00:00,1013.6,16.2,90.6,45.4,316.7,5.5,0.0,cloudy

 ### Quick helper: `get_daily_forecast`

 `get_daily_forecast` returns a pandas DataFrame directly with daily summaries,

In [7]:
daily_df = api.get_daily_forecast(
    latitude=coordinates.latitude,
    longitude=coordinates.longitude,
    days=5,
)

daily_df  # Already a DataFrame!

                    DEBUG    🌐 Constructed URL:
                             https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=-31.651&lon=116.659

                    DEBUG    📋 User-Agent: weather-tools/0.0.0 (Python 3.13)

                    DEBUG    Cache hit for request: e9450af0091badb1a028399707618845

,date,daily_rain,max_temp,min_temp,mslp,relative_humidity,wind_speed,wind_speed_max,cloud_fraction,weather_symbol
0,2026-05-27,7.3,16.2,13.5,1013.358333,64.608333,4.316667,5.6,67.183333,heavyrainshowers_night
1,2026-05-28,0.3,20.1,9.2,1015.487500,80.341667,3.266667,6.1,25.883333,lightrainshowers_day
2,2026-05-29,0.1,18.8,9.4,1016.166667,77.612500,2.050000,3.9,58.820833,lightrainshowers_day
3,2026-05-30,8.0,19.5,10.5,1008.700000,77.375000,4.275000,6.6,42.575000,lightrainshowers_day
4,2026-05-31,8.8,14.8,10.5,1002.175000,82.250000,8.200000,9.1,56.225000,rainshowers_day

## 4. Merge met.no forecasts with SILO history

 Pull the last five days from the SILO DataDrill API for the same coordinates,

 then merge that history with the met.no forecast. The helper automatically

 converts column names, fills optional variables (when enabled), and annotates

 the data source for each record.

In [8]:
first_forecast_date = pd.to_datetime(daily_df["date"]).min()
# history_end = first_forecast_date - pd.Timedelta(days=1)
history_start = first_forecast_date - pd.Timedelta(days=4)
silo_api = SiloAPI(log_level="INFO")
silo_history, _ = silo_api.get_data_drill(
    latitude=coordinates.latitude,
    longitude=coordinates.longitude,
    start_date=history_start.strftime("%Y%m%d"),
    end_date=first_forecast_date.strftime("%Y%m%d"),
    variables=["daily_rain", "max_temp", "min_temp", "et_short_crop", "mslp"],
)

merged = merge_historical_and_forecast(
    silo_data=silo_history,
    metno_data=daily_df,
    overlap_strategy="prefer_silo",
    return_cols="all",
)

merged

                    INFO     Using cached response. Clear cache with: weather-tools silo cache --clear

                    INFO     Auto-detected transition date: 2026-05-27 00:00:00

                    INFO     Merged 4 SILO records with 5 met.no records. Total: 9 records

,latitude,longitude,daily_rain,max_temp,min_temp,et_short_crop,mslp,date,data_source,is_forecast,relative_humidity,wind_speed,wind_speed_max,cloud_fraction,weather_symbol,forecast_generated_at
0,-31.651,116.659,0.0,17.9,-0.2,2.1,1028.400000,2026-05-23,silo,False,NaN,NaN,NaN,NaN,NaN,NaT
1,-31.651,116.659,0.0,20.3,-0.3,2.4,1030.300000,2026-05-24,silo,False,NaN,NaN,NaN,NaN,NaN,NaT
2,-31.651,116.659,0.0,23.2,1.2,2.7,1027.700000,2026-05-25,silo,False,NaN,NaN,NaN,NaN,NaN,NaT
3,-31.651,116.659,0.0,19.8,6.9,2.4,1024.000000,2026-05-26,silo,False,NaN,NaN,NaN,NaN,NaN,NaT
4,NaN,NaN,7.3,16.2,13.5,NaN,1013.358333,2026-05-27,metno,True,64.608333,4.316667,5.6,67.183333,heavyrainshowers_night,2026-05-27 12:21:08.607587+00:00
5,NaN,NaN,0.3,20.1,9.2,NaN,1015.487500,2026-05-28,metno,True,80.341667,3.266667,6.1,25.883333,lightrainshowers_day,2026-05-27 12:21:08.607587+00:00
6,NaN,NaN,0.1,18.8,9.4,NaN,1016.166667,2026-05-29,metno,True,77.612500,2.050000,3.9,58.820833,lightrainshowers_day,2026-05-27 12:21:08.607587+00:00
7,NaN,NaN,8.0,19.5,10.5,NaN,1008.700000,2026-05-30,metno,True,77.375000,4.275000,6.6,42.575000,lightrainshowers_day,2026-05-27 12:21:08.607587+00:00
8,NaN,NaN,8.8,14.8,10.5,NaN,1002.175000,2026-05-31,metno,True,82.250000,8.200000,9.1,56.225000,rainshowers_day,2026-05-27 12:21:08.607587+00:00

In [9]:
merge_summary = get_merge_summary(merged)
merge_summary

{'total_records': 9,
 'silo_records': np.int64(4),
 'metno_records': np.int64(5),
 'date_range': {'start': Timestamp('2026-05-23 00:00:00'),
  'end': Timestamp('2026-05-31 00:00:00'),
  'days': 9},
 'silo_period': {'start': Timestamp('2026-05-23 00:00:00'),
  'end': Timestamp('2026-05-26 00:00:00')},
 'metno_period': {'start': Timestamp('2026-05-27 00:00:00'),
  'end': Timestamp('2026-05-31 00:00:00')},
 'transition_date': Timestamp('2026-05-27 00:00:00')}

## 4b. Merge Forecast with SILO PatchedPoint 

 Pull the last four days from the SILO Patch Point API for the same coordinates, using the station code.

In [10]:
first_forecast_date = pd.to_datetime(daily_forecasts["date"]).min()
history_end = first_forecast_date  # - pd.Timedelta(days=1) # Include day before forecast to check overlap handling
history_start = history_end - pd.Timedelta(days=4)


silo_station_data, _ = silo_api.get_patched_point(
    station_code=str(station_meta["station_code"]),
    start_date=history_start.strftime("%Y%m%d"),
    end_date=history_end.strftime("%Y%m%d"),
    variables=["daily_rain", "max_temp", "min_temp", "et_short_crop", "vp"],
)

merge_historical_and_forecast(
    silo_data=silo_station_data,
    metno_data=daily_df,
    return_cols="all",
)

                    INFO     Using cached response. Clear cache with: weather-tools silo cache --clear

                    INFO     Auto-detected transition date: 2026-05-27 00:00:00

                    WARNING  Converting met.no relative_humidity (%) -> vp (vapour pressure, hPa) using mean daily
                             temperature; the SILO 'vp' column is vapour pressure, not relative humidity.

                    INFO     Merged 4 SILO records with 5 met.no records. Total: 9 records

,station,daily_rain,max_temp,min_temp,et_short_crop,vp,date,data_source,is_forecast,mslp,relative_humidity,wind_speed,wind_speed_max,cloud_fraction,weather_symbol,forecast_generated_at
0,10111.0,0.0,17.8,-0.4,2.2,6.500000,2026-05-23,silo,False,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,10111.0,0.0,20.2,-0.4,2.4,6.900000,2026-05-24,silo,False,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,10111.0,0.0,23.2,0.6,2.6,8.400000,2026-05-25,silo,False,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,10111.0,0.0,19.8,2.8,2.3,7.600000,2026-05-26,silo,False,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,NaN,7.3,16.2,13.5,NaN,10.890564,2026-05-27,metno,True,1013.358333,64.608333,4.316667,5.6,67.183333,heavyrainshowers_night,2026-05-27 12:21:08.678315+00:00
5,NaN,0.3,20.1,9.2,NaN,13.369154,2026-05-28,metno,True,1015.487500,80.341667,3.266667,6.1,25.883333,lightrainshowers_day,2026-05-27 12:21:08.678315+00:00
6,NaN,0.1,18.8,9.4,NaN,12.463883,2026-05-29,metno,True,1016.166667,77.612500,2.050000,3.9,58.820833,lightrainshowers_day,2026-05-27 12:21:08.678315+00:00
7,NaN,8.0,19.5,10.5,NaN,13.169092,2026-05-30,metno,True,1008.700000,77.375000,4.275000,6.6,42.575000,lightrainshowers_day,2026-05-27 12:21:08.678315+00:00
8,NaN,8.8,14.8,10.5,NaN,12.017940,2026-05-31,metno,True,1002.175000,82.250000,8.200000,9.1,56.225000,rainshowers_day,2026-05-27 12:21:08.678315+00:00

In [11]:
daily_df

,date,daily_rain,max_temp,min_temp,mslp,relative_humidity,wind_speed,wind_speed_max,cloud_fraction,weather_symbol
0,2026-05-27,7.3,16.2,13.5,1013.358333,64.608333,4.316667,5.6,67.183333,heavyrainshowers_night
1,2026-05-28,0.3,20.1,9.2,1015.487500,80.341667,3.266667,6.1,25.883333,lightrainshowers_day
2,2026-05-29,0.1,18.8,9.4,1016.166667,77.612500,2.050000,3.9,58.820833,lightrainshowers_day
3,2026-05-30,8.0,19.5,10.5,1008.700000,77.375000,4.275000,6.6,42.575000,lightrainshowers_day
4,2026-05-31,8.8,14.8,10.5,1002.175000,82.250000,8.200000,9.1,56.225000,rainshowers_day